#!/bin/bash
set -e

#
# generate_unity.sh — Auto-generate per-module lexbor unity build files.
#
# Mirrors CMake's GLOB_RECURSE approach: scans lexbor/source/lexbor/*/
# for .c files and generates unity .c files grouped by module.
#
# Run this after updating the lexbor submodule to regenerate.
#

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
LEXBOR_SOURCE="$SCRIPT_DIR/lexbor/source"

if [ ! -d "$LEXBOR_SOURCE/lexbor" ]; then
    echo "Error: lexbor source not found at $LEXBOR_SOURCE"
    echo "Run 'bash setup.sh' first to fetch the lexbor source."
    exit 1
fi

# ── Configuration ─────────────────────────────────────────────────────
#
# Module → unity file grouping.
# Modules that share static symbol names must be in separate groups.
#
# Known conflicts (lexbor v2.6.0):
#   - dom/interfaces/document.c vs style/dom/interfaces/document.c
#     → dom and style are in separate groups
#   - html/interface.c vs html/interfaces/document.c (via interface_res.h)
#     → html/interface.c excluded from unity, compiled separately
#   - css/value.c vs css/syntax/syntax.c
#     → css/value.c excluded from unity, compiled separately

# Files excluded from unity builds due to static symbol conflicts.
# These are compiled as separate translation units via #flag in bindings.v.
EXCLUDED="lexbor/html/interface.c lexbor/css/value.c"

# ── Helpers ───────────────────────────────────────────────────────────

is_excluded() {
    for excl in $EXCLUDED; do
        if [ "$1" = "$excl" ]; then
            return 0
        fi
    done
    return 1
}

# find_sources MODULE — glob all .c files for a module (like CMake's GLOB_RECURSE)
find_sources() {
    find "$LEXBOR_SOURCE/lexbor/$1" -name "*.c" -type f 2>/dev/null | sort
}

# write_includes OUTPUT MODULE... — append #include lines for each module's .c files
write_includes() {
    local out="$1"; shift
    for mod in "$@"; do
        if [ ! -d "$LEXBOR_SOURCE/lexbor/$mod" ]; then
            echo "  Warning: module '$mod' not found, skipping"
            continue
        fi
        echo "/* $mod */" >> "$out"
        find_sources "$mod" | while read -r filepath; do
            local rel="${filepath#$LEXBOR_SOURCE/}"
            if is_excluded "$rel"; then
                echo "/* excluded: $rel (separate TU) */" >> "$out"
            else
                echo "#include \"$rel\"" >> "$out"
            fi
        done
        echo "" >> "$out"
    done
}

# write_header OUTPUT MODULES_DESC — write the file header
write_header() {
    cat > "$1" <<EOF
/*
 * Auto-generated by generate_unity.sh — do not edit manually.
 * Lexbor modules: $2
 */

#define LEXBOR_STATIC
EOF
}

# ── Generate each group ───────────────────────────────────────────────

echo "Generating lexbor unity build files from $LEXBOR_SOURCE ..."

# ── core (+ platform ports) ──

OUT="$SCRIPT_DIR/lexbor_core.c"
write_header "$OUT" "core"
cat >> "$OUT" <<'EOF'

#ifndef _DEFAULT_SOURCE
    #define _DEFAULT_SOURCE
#endif
#ifndef _BSD_SOURCE
    #define _BSD_SOURCE
#endif

EOF
write_includes "$OUT" core
cat >> "$OUT" <<'EOF'
/* ports */
#ifdef _WIN32
EOF
find "$LEXBOR_SOURCE/lexbor/ports/windows_nt" -name "*.c" -type f | sort | while read -r f; do
    echo "    #include \"${f#$LEXBOR_SOURCE/}\"" >> "$OUT"
done
echo "#else" >> "$OUT"
find "$LEXBOR_SOURCE/lexbor/ports/posix" -name "*.c" -type f | sort | while read -r f; do
    echo "    #include \"${f#$LEXBOR_SOURCE/}\"" >> "$OUT"
done
echo "#endif" >> "$OUT"
echo "  Generated $OUT"

# ── dom ──

OUT="$SCRIPT_DIR/lexbor_dom.c"
write_header "$OUT" "dom"
echo "" >> "$OUT"
write_includes "$OUT" dom
echo "  Generated $OUT"

# ── html (interface.c excluded → separate TU) ──

OUT="$SCRIPT_DIR/lexbor_html.c"
write_header "$OUT" "html"
echo "" >> "$OUT"
write_includes "$OUT" html
echo "  Generated $OUT"

# ── css (value.c excluded → separate TU) ──

OUT="$SCRIPT_DIR/lexbor_css.c"
write_header "$OUT" "css"
echo "" >> "$OUT"
write_includes "$OUT" css
echo "  Generated $OUT"

# ── extra (all remaining modules) ──

OUT="$SCRIPT_DIR/lexbor_extra.c"
write_header "$OUT" "ns tag selectors encoding engine style punycode unicode url utils"
echo "" >> "$OUT"
write_includes "$OUT" ns tag selectors encoding engine style punycode unicode url utils
echo "  Generated $OUT"

# ── Summary ──

echo ""
echo "Done. Excluded files (compiled as separate TUs via bindings.v):"
for f in $EXCLUDED; do
    echo "  - $f"
done
