/*
 * Auto-generated by generate_unity.sh — do not edit manually.
 * Lexbor modules: ns tag selectors encoding engine style punycode unicode url utils
 */

#define LEXBOR_STATIC

/* ns */
#include "lexbor/ns/ns.c"

/* tag */
#include "lexbor/tag/tag.c"

/* selectors */
#include "lexbor/selectors/selectors.c"

/* encoding */
#include "lexbor/encoding/decode.c"
#include "lexbor/encoding/encode.c"
#include "lexbor/encoding/encoding.c"
#include "lexbor/encoding/multi.c"
#include "lexbor/encoding/range.c"
#include "lexbor/encoding/res.c"
#include "lexbor/encoding/single.c"

/* engine */
#include "lexbor/engine/engine.c"

/* style */
#include "lexbor/style/dom/interfaces/document.c"
#include "lexbor/style/dom/interfaces/element.c"
#include "lexbor/style/event.c"
#include "lexbor/style/html/interfaces/document.c"
#include "lexbor/style/html/interfaces/style_element.c"
#include "lexbor/style/style.c"

/* punycode */
#include "lexbor/punycode/punycode.c"

/* unicode */
#include "lexbor/unicode/idna.c"
#include "lexbor/unicode/unicode.c"

/* url */
#include "lexbor/url/url.c"

/* utils */
#include "lexbor/utils/http.c"
#include "lexbor/utils/warc.c"

