/*
 * Auto-generated by generate_unity.sh — do not edit manually.
 * Lexbor modules: core
 */

#define LEXBOR_STATIC

#ifndef _DEFAULT_SOURCE
    #define _DEFAULT_SOURCE
#endif
#ifndef _BSD_SOURCE
    #define _BSD_SOURCE
#endif

/* core */
#include "lexbor/core/array.c"
#include "lexbor/core/array_obj.c"
#include "lexbor/core/avl.c"
#include "lexbor/core/bst.c"
#include "lexbor/core/bst_map.c"
#include "lexbor/core/conv.c"
#include "lexbor/core/diyfp.c"
#include "lexbor/core/dobject.c"
#include "lexbor/core/dtoa.c"
#include "lexbor/core/hash.c"
#include "lexbor/core/in.c"
#include "lexbor/core/mem.c"
#include "lexbor/core/mraw.c"
#include "lexbor/core/plog.c"
#include "lexbor/core/print.c"
#include "lexbor/core/serialize.c"
#include "lexbor/core/shs.c"
#include "lexbor/core/str.c"
#include "lexbor/core/strtod.c"
#include "lexbor/core/utils.c"

/* ports */
#ifdef _WIN32
    #include "lexbor/ports/windows_nt/lexbor/core/fs.c"
    #include "lexbor/ports/windows_nt/lexbor/core/memory.c"
    #include "lexbor/ports/windows_nt/lexbor/core/perf.c"
#else
    #include "lexbor/ports/posix/lexbor/core/fs.c"
    #include "lexbor/ports/posix/lexbor/core/memory.c"
    #include "lexbor/ports/posix/lexbor/core/perf.c"
#endif
