/*
 * Auto-generated by generate_unity.sh — do not edit manually.
 * Lexbor modules: dom
 */

#define LEXBOR_STATIC

/* dom */
#include "lexbor/dom/collection.c"
#include "lexbor/dom/exception.c"
#include "lexbor/dom/interface.c"
#include "lexbor/dom/interfaces/attr.c"
#include "lexbor/dom/interfaces/cdata_section.c"
#include "lexbor/dom/interfaces/character_data.c"
#include "lexbor/dom/interfaces/comment.c"
#include "lexbor/dom/interfaces/document.c"
#include "lexbor/dom/interfaces/document_fragment.c"
#include "lexbor/dom/interfaces/document_type.c"
#include "lexbor/dom/interfaces/element.c"
#include "lexbor/dom/interfaces/event_target.c"
#include "lexbor/dom/interfaces/node.c"
#include "lexbor/dom/interfaces/processing_instruction.c"
#include "lexbor/dom/interfaces/shadow_root.c"
#include "lexbor/dom/interfaces/text.c"

